[package]
name = "tbl_verification"
version = "0.3.2"
edition = "2024"

[dependencies]
path_lib = { path = "../path_lib" }
tbl_structures = { path = "../structures" }
tbl_textualization = { path = "../textualization" }

dyn-clone = { version = "1.0.19" }
itertools = { version = "0.14.0" }
